version: '3.8'
services:
  pokemon:
    image: postgres:14.1-alpine
    ports:
      - "5003:5003"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokemon