version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    ports:
      - "5003:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokemon
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "npx prisma migrate deploy && npx prisma generate && npm start"
    container_name: pokemonApi
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pokemon
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
